### ISSUE TITLE
Amazon Prime Video Issue

### ISSUE THREAD

**Issue by Phoenomenal** [gignupg/Movie-Subtitles-Chrome-Extension#1]
Hello,

Extensions doesn't work on Amazon Prime Video  (primevideo.com)  It detect video frame but when i click on Load subtitles nothing happens.   Works great on other websites such as Netflix and youtube.

Can you please look at that and fix if possible ?

**Comment by gignupg** [comment]
Hi, thanks for reporting this! I tried to reproduce it but I can't reach primevideo.com. I mean I can reach the website but I can't do anything there. They try to redirect me to amazon.de.

![primevideo](https://user-images.githubusercontent.com/52784332/137094274-d95e2c1e-3dba-43b0-abed-6df1bbdc6f2b.png)
I'll gladly have a look at it, once I've figured out how to get to primevideo.com.

**Comment by Phoenomenal** [comment]
Hello,  there is only Germany, UK, USA, Japan i believe who watch primevideo on Amazon main site.   With VPN i choose Germany and i get exactly same message.   To go on Primevideo.com you need to sign in with your main prime account on that page www.primevideo.com.    Made a red line to upper right corner and you are sigh in to the primevideo.com site where all of us living outside the 4 countries i mentioned above watch all amazon prime video content.   Thank you in advance!!!

![Screenshot_7](https://user-images.githubusercontent.com/68902338/137098268-b72f3696-2520-496e-8be9-83b84950820c.png)

**Comment by gignupg** [comment]
Thx! I was able to reach primevideo.com via a VPN. But everything works fine!
![primevideo working](https://user-images.githubusercontent.com/52784332/137101358-4e14c608-9f03-4528-878f-90cd0b344101.png)

**Comment by gignupg** [comment]
Can you please open primevideo.com in incognito and see if that works? In incognito most of your chrome extensions will be disabled by default. So you'll have to enable movie subtitles for incognito. Make sure that movie subtitles is the only extension enabled. Sometimes other extensions are interfering with movie subtitles. I've had this happen before...

**Comment by Phoenomenal** [comment]
Did that. The same thing in incognito with your extension being the only one enabled, i click on  Load subtitles  and nothing at all happens.      I use Edge browser,   but just for tests have Chrome and the same thing here as well in both normal and incognito mode with movie subtitles being the  only one enabled extension.     Very strange.

Its probably unlikely but im on Windows 11,  who knows  maybe something to do with that.....

**Comment by Phoenomenal** [comment]
Wow,  its freaking strange.   Dont work for Goliath,  Good Omen  but work on Mr.Robot,  Vinland Saga

It seems only some Amazon Originals dont work.   Goliath, Good Omen,  Boys  wont work.   Some others work,  and other video also work including all anime.     Can you also test  these series ?  

But overall its working.   Its just when i was testing i was watching Goliath and then try on Boys and seems it doesnt work i thought  extension dont work on primevideo.   Who would sought only some of titles doesnt work ))

**Comment by gignupg** [comment]
Wow, that's really strange!

Unfortunately, the only thing I can test with the VPN is the trailers of movies and that seems to work. For Goliath and Good Omen I can't even see the trailer. Once I log in Amazon notices that I'm using a VPN and redirect me to amazon.de.
![test](https://user-images.githubusercontent.com/52784332/137113365-2a3b5f51-1486-4ecb-994e-8785613e944e.png)

**Comment by Phoenomenal** [comment]
Seems its unlikely primevideo.com domain issues  since many (if not most)  titles work just fine its safe to say on amazon.de will be the same thing.  Unfortunately i cant test  amazon.de even with Germany VPN because my account only work on primevideo.com.  Or you could access  with your ISP Germany IP adress without vpn  if click sign in  on upper right page
![Screenshot_7](https://user-images.githubusercontent.com/68902338/137116475-1fee2420-ae24-4e07-8cf9-2d07333ab206.png)

**Comment by gignupg** [comment]
Hmm, on amazon.de Goliath and Good Omen both work flawlessly for me!

**Comment by Phoenomenal** [comment]
Thanks for the info.  Well after testing many titles i say about 80 percent  videos extension work for me so its good. 

I noticed another problem not related to Amazon, but to extensioin itself :  unfortunately does not properly display subtitles that normally present text at the top side of the screen and text at the bottom side of the screen at the same time. This is more common in anime (for example, there is a conversation in the background or an inscription pops up and at the same time another conversation or thoughts of the character on the plan or notes appear. There is an example in the attachment) but in Movie-Subtitles  this does not happen and the text lines kinda interrupts each other (i mean 2-nd line will appear for a second and then other line replace it but they need to be at the same time)    I think it will be possible to fix it, because in another chrome extension (+ sub) text appears one above the other in such places (i mean not exactly in upper and lower half of the screen like in example but one line appear above another). Example how it looks on +sub extension also in attachment
https://drive.google.com/file/d/1fMpDq6bB7LwKOkGegLAV2zMmBSsQ_lp0/view?usp=sharing  -    if interesting this is srt  sub file for this video.  Very easy to test because there are a few lines like this  during first 30-40 seconds of video so you could easly test it on any video and you see what i mean when those lines begin interrupt each other instead of showing at the same time.
  
![example](https://user-images.githubusercontent.com/68902338/137208515-e59492e4-7c04-4a30-a05d-604dcfbacc02.png)
 
![Screenshot_2](https://user-images.githubusercontent.com/68902338/137209769-7a184a1e-7757-4887-8c7d-059674208363.png)

**Comment by gignupg** [comment]
Thx for letting me know! Could you copy your last message and create a new issue for it? Because it isn't related to the Amazon Prime Video issue. I'll close this one then!
